[project]
name = "BaseTelegramBot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.20.0.post0",
    "aiosqlite>=0.21.0",
    "apscheduler>=3.11.0",
    "apscheduler-di>=0.1.0",
    "asyncpg>=0.30.0",
    "dotenv>=0.9.9",
    "loguru>=0.7.3",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "python-decouple>=3.8",
    "pytz>=2025.2",
    "redis>=6.0.0",
    "ruff>=0.11.7",
    "setuptools>=80.1.0",
    "six>=1.17.0",
    "sqlalchemy>=2.0.40",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
